from django import forms
from .models import Farmer, Attendance

#Form for Farmer model

class FarmerForm(forms.ModelForm):
    class Meta:
        model = Farmer
        fields = ['name','farm','age','gender', 'contract']
       
       #to get all fields at the same time without specifying them
       # fields='__all__' 

        widgets = {
            'name':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter farmer name'
        }),
         'farm':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Enter farm name'
        }),
         'age': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter farmer age'
            }),
        'gender': forms.RadioSelect(attrs={'class': 'form-check-input'}), 
        'contract': forms.Select(attrs={'class': 'form-select'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove any autogenerated empty choice like ('', '---------') for contract
        if 'contract' in self.fields:
            choices = self.fields['contract'].choices
            self.fields['contract'].choices = [c for c in choices if c[0] != '']
        # Ensure gender has no empty/dashed option
        if 'gender' in self.fields:
            gchoices = self.fields['gender'].choices
            self.fields['gender'].choices = [c for c in gchoices if c[0] != '']

