# Generated by Django 5.2.7 on 2025-10-21 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='contract',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary')], default='CASUAL', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 10, 21, 8, 3, 3, 402635, tzinfo=datetime.timezone.utc)),
        ),
    ]
